[package]
name = "polywrap-wasm-rs"
version = "0.0.1-prealpha-dev.37.4"
license = "MIT"
description = "Polywrap's Rust-Wasm Runtime"
homepage = "https://polywrap.io"
documentation = "https://docs.polywrap.io"
repository = "https://github.com/polywrap/monorepo"
authors = [
  "Kobby Pentangeli <kobbypentangeli@gmail.com>",
  "Jordan Ellis <jelli@dorg.tech>"
]
keywords = ["polywrap", "wasm", "webassembly"]
categories = ["wasm"]
edition = "2021"

[dependencies]
num-bigint = { version = "0.4", default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'