[package]
name = "polywrap-wasm-rs"
version = "0.11.3"
license = "MIT"
description = "Polywrap's Rust-Wasm Runtime"
homepage = "https://polywrap.io"
documentation = "https://docs.polywrap.io"
repository = "https://github.com/polywrap/monorepo"
authors = [
  "Kobby Pentangeli <kobbypentangeli@gmail.com>",
  "Jordan Ellis <jelli@dorg.tech>",
  "Nestor Amesty <nestor@dorg.tech>"
]
keywords = ["polywrap", "wasm", "webassembly"]
categories = ["wasm"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
byteorder = "1.4.3"
thiserror = "1.0.30"
polywrap_msgpack_serde = "0.0.2-beta.7"

[dev-dependencies]
serde = { version = "1.0.136", default-features = false, features = ["derive"] }

[profile.release]
opt-level = 's'
lto = true
panic = 'abort'
