version: '3'
services:
  dev-server:
    build: ./
    ports:
      - '${DEV_SERVER_PORT}:${DEV_SERVER_PORT}'
    links:
      - ganache
    environment:
      ganache: 'ganache:${ETHEREUM_PORT}'
      DEV_SERVER_PORT: '${DEV_SERVER_PORT}'
  ganache:
    image: 'trufflesuite/ganache-cli:v6.12.2'
    ports:
      - '${ETHEREUM_PORT}:8545'
    command: -l 8000000 --networkId 1576478390085 --deterministic --hostname=0.0.0.0
