[tool.poetry]
name = "polywrap-wasm"
version = "0.1.0"
description = ""
authors = ["Cesar <cesarbrazon10@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
polywrap-core = { path = "../polywrap-core", develop = false }
polywrap-msgpack = { path = "../polywrap-msgpack", develop = false }
wasmtime = "^1.0.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
