[tool.poetry]
name = "polywrap-wasm"
version = "0.1.0"
description = ""
authors = ["Cesar <cesarbrazon10@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
wasmtime = "^1.0.1"
polywrap-core = { path = "../polywrap-core", develop = true }
polywrap-msgpack = { path = "../polywrap-msgpack", develop = true }
unsync = "^1.4.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
black = "^22.10.0"
pytest-asyncio = "^0.19.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
