format: 0.2.0
project:
  name: deploy-sanity
  type: wasm/assemblyscript
source:
  schema: ./schema.graphql
  module: ./src/index.ts
extensions:
  build: ./polywrap.build.yaml
  deploy: ./polywrap.deploy.yaml
