[tool.poetry]
name = "polywrap-client"
version = "0.1.0"
description = ""
authors = ["Cesar <cesarbrazon10@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
wasmtime = "^1.0.1"
polywrap-core = { path = "../polywrap-core", develop = true }
polywrap-uri-resolvers = { path = "../polywrap-uri-resolvers", develop = true }
unsync = "^1.4.0"


[tool.poetry.dev-dependencies]
black = "^22.10.0"
pytest = "^7.1.3"
pytest-asyncio = "^0.19.0"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
