[package]
name = "client-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "1.0.1"
rmp-serde = "1.1.1"
tokio = { version = "1", features = ["full"] }