[package]
name = "query"
version = "0.1.0"
description = "Query module of Ethereum polywrapper"
authors = [
  "Kobby Pentangeli <kobbypentangeli@gmail.com>",
  "Jordan Ellis <jelli@dorg.tech>"
]
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2021"

[features]
w3invoke = []

[dependencies]
async-trait = "0.1.51"
ethers = "0.6.1"
thiserror = "1.0.30"
tokio = { version = "1.4.0", features = ["rt"] }
getrandom = { version = "*", features = ["js"] }
num-traits = { version = "0.2", default-features = false }
polywrap-wasm-rs = { version = "0.0.1-prealpha-dev.37.4", path = "../../../../wasm/rs" }
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'