format: 0.1.0
name: "Migration_sample"
language: wasm/assemblyscript
schema: ../schema.graphql
module: ../index.ts
build: ./polywrap.build.yaml
meta: ./polywrap.meta.yaml
deploy: ./polywrap.deploy.yaml
import_redirects:
  - uri: "wrap://ens/some.domain.eth"
    schema: ../some/path