format: 0.3.0
project:
  name: "Migration_sample"
  type: wasm/assemblyscript
source:
  schema: ../schema.graphql
  module: ../index.ts
  import_abis:
  - uri: "ens/ipfs.polywrap.eth"
    abi: ../../../../../../../../interfaces/ipfs/build/schema.graphql
extensions:
  build: ./polywrap.build.yaml
  meta: ./polywrap.meta.yaml
  deploy: ./polywrap.deploy.yaml