format: 0.0.1-prealpha.1
stages:
  ipfs_deploy:
    package: ipfs
    uri: fs/./build
  from_deploy:
    package: ens
    depends_on: ipfs_deploy
    config:
      domainName: $DOMAIN_NAME
      provider: 'http://localhost:8545'
      ensRegistryAddress: '0x9b1f7F645351AF3631a656421eD2e40f2802E6c0'
  from_deploy2:
    package: ens
    depends_on: ipfs_deploy
    config:
      domainName: test2.eth
      provider: 'http://localhost:8545'
      ensRegistryAddress: '0x9b1f7F645351AF3631a656421eD2e40f2802E6c0'
  from_uri:
    package: ens
    uri: ipfs/QmVdDR6QtigTt38Xwpj2Ki73X1AyZn5WRCreBCJq1CEtpF
    config:
      domainName: test3.eth
      provider: 'http://localhost:8545'
      ensRegistryAddress: '0x9b1f7F645351AF3631a656421eD2e40f2802E6c0'
