name: CI-Javascript

on:
  push:
    branches:
      - origin
      - origin-dev
  pull_request:

jobs:
  Lint-and-Build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline

      - name: Lint
        run: yarn run lint:ci

      - name: Build
        run: yarn build

  CI-WRAP-Test-Harness:
    uses: ./.github/workflows/ci-wrap-test-harness.yaml

  Test-Core:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: ${{ always() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.4.2'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.13.1'

      - name: Install cue lang
        run: go install cuelang.org/go/cmd/cue@latest

      - name: Check if cue is installed
        run: cue version

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test:core

  Test-Client:
    runs-on: ubuntu-latest
    needs: CI-WRAP-Test-Harness
    if: ${{ always() }}
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline

      - name: Build
        run: yarn build

      - name: Get updated wrappers
        if: ${{ needs.CI-WRAP-Test-Harness.outputs.rebuild_required == 'true' }}
        uses: actions/download-artifact@v3
        id: get-wrappers
        with:
          name: rebuilt-wrappers
          path: ./wrappers

      - if: ${{ needs.CI-WRAP-Test-Harness.outputs.rebuild_required == 'true' }}
        run: |
          rm -rf packages/test-cases/cases/wrappers
          mv wrappers packages/test-cases/cases

      - name: Test
        run: yarn test:client

  Test-Cli:
    runs-on: ubuntu-latest
    needs: CI-WRAP-Test-Harness
    if: ${{ always() }}
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.13.1'

      - name: Install cue lang
        run: go install cuelang.org/go/cmd/cue@latest

      - name: Check if cue is installed
        run: cue version

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline

      - name: Build
        run: yarn build

      - name: Get updated wrappers
        if: ${{ needs.CI-WRAP-Test-Harness.outputs.rebuild_required == 'true' }}
        uses: actions/download-artifact@v3
        id: get-wrappers
        with:
          name: rebuilt-wrappers
          path: ./wrappers

      - if: ${{ needs.CI-WRAP-Test-Harness.outputs.rebuild_required == 'true' }}
        run: |
          rm -rf packages/test-cases/cases/wrappers
          mv wrappers packages/test-cases/cases

      - name: Test cli:unit
        run: yarn test:cli:unit

      - name: Test cli:e2e:p1
        run: yarn test:cli:e2e:p1

      - name: Test cli:e2e:p2
        run: yarn test:cli:e2e:p2
