name: Publish-Releases
on:
  # When Pull Request is merged
  pull_request_target:
    types: [closed]

jobs:
  Publish-GitHub-Release:
    name: GitHub Release
    if: |
      github.event.pull_request.user.login == 'polywrap-build-bot' &&
      github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Read VERSION into env.RELEASE_VERSION
        run: echo RELEASE_VERSION=$(cat VERSION) >> $GITHUB_ENV

      - name: Set Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{github.repository}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check If Tag Exists
        id: tag_check
        shell: bash -ex {0}
        run: |
          GET_API_URL="https://api.github.com/repos/${{github.repository}}/git/ref/tags/${{env.RELEASE_VERSION}}"
          http_status_code=$(curl -LI $GET_API_URL -o /dev/null -w '%{http_code}\n' -s \
            -H "Authorization: token ${GITHUB_TOKEN}")
          if [ "$http_status_code" -ne "404" ] ; then
            echo TAG_EXISTS=true >> $GITHUB_ENV
          else
            echo TAG_EXISTS=false >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Git Tag
        if: ${{env.TAG_EXISTS}} == 'false'
        uses: azu/action-package-version-to-git-tag@v1
        with:
          version: ${{ env.RELEASE_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Create Release
        id: create_release
        if: ${{env.TAG_EXISTS}} == 'false' && github.event.pull_request.merged == true
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          # Copy Pull Request's tile and body to Release Note
          release_name: ${{ github.event.pull_request.title }}
          body: |
            ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false

      - uses: actions/github-script@0.8.0
        if: ${{env.TAG_EXISTS}} == 'false'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '**[GitHub Release Published](https://github.com/${{ github.repository }}/releases/tag/${{ env.RELEASE_VERSION }}) `${{env.RELEASE_VERSION}}`** ðŸŽ‰'
            })

  Publish-NPM-Release:
    name: NPM Release
    if: |
      github.event.pull_request.user.login == 'polywrap-build-bot' &&
      github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Read VERSION into env.RELEASE_VERSION
        run: echo RELEASE_VERSION=$(cat VERSION) >> $GITHUB_ENV

      - name: Read .nvmrc into env.NVMRC
        run: echo NVMRC=$(cat .nvmrc) >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '${{env.NVMRC}}'

      - name: Auth into NPM
        if: ${{env.TAG_EXISTS}} == 'false'
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken=${{secrets.POLYWRAP_BUILD_BOT_NPM_PAT}}
          echo $(npm whoami --registry https://registry.npmjs.org/)

      - name: Install JS dependencies
        if: ${{env.TAG_EXISTS}} == 'false'
        run: yarn install --nonInteractive --frozen-lockfile

      - name: Build JS packages
        if: ${{env.TAG_EXISTS}} == 'false'
        run: yarn build

      - name: Publish Node Packages To NPM
        if: ${{env.TAG_EXISTS}} == 'false'
        run: yarn publish:npm
        env:
          NPM_AUTH_TOKEN: ${{secrets.POLYWRAP_BUILD_BOT_NPM_PAT}}

      - uses: actions/github-script@0.8.0
        if: ${{env.TAG_EXISTS}} == 'false'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '**[NPM Release Published](https://www.npmjs.com/search?q=polywrap) `${{env.RELEASE_VERSION}}`** ðŸŽ‰'
            })

  Publish-Crates-dot-io-Release:
    name: crates.io Release
    if: |
      github.event.pull_request.user.login == 'polywrap-build-bot' &&
      github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Read VERSION into env.RELEASE_VERSION
        run: echo RELEASE_VERSION=$(cat VERSION) >> $GITHUB_ENV

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build RS crates
        if: ${{env.TAG_EXISTS}} == 'false'
        working-directory: ./packages/wasm/rs
        run: cargo build --release

      - name: Verify & Generate RS Documentation
        if: ${{env.TAG_EXISTS}} == 'false'
        working-directory: ./packages/wasm/rs
        run: cargo doc --no-deps

      - name: Upload Rust Crates To Crates.io
        if: ${{env.TAG_EXISTS}} == 'false'
        working-directory: ./packages/wasm/rs
        run: cargo publish --token ${{secrets.POLYWRAP_BUILD_BOT_CRATES_PAT}}

      - uses: actions/github-script@0.8.0
        if: ${{env.TAG_EXISTS}} == 'false'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '**[Crates.io Release Published](https://crates.io/search?q=polywrap) `${{env.RELEASE_VERSION}}`** ðŸŽ‰'
            })
